<?php
/**
 * The template for displaying a single field
 *
 * This template can be overridden by copying it to yourtheme/elzo-forms/field.php.
 *
 * HOWEVER, on occasion Elzo Forms will need to update template files and you
 * (the theme developer) will need to copy the new files to your theme to
 * maintain compatibility. We try to do this as little as possible, but it does
 * happen. When this occurs the version of the template file will be bumped and
 * the readme will list any important changes.
 *
 * @see         Plugin documentation
 * @package     ElzoForms\Templates
 * @version     1.2.0
 *
 * @var \ElzoForms\Field\Field $field Field object
 * @var int $form_id Form ID
 * @var int $step_index Step index
 * @var array $form_settings Form settings
 * @var array $texts_settings Text settings
 * @var array $field_data All field data prepared by $field->get_data()
 * @var string $id Field HTML ID attribute
 * @var string $label Field label
 * @var bool $required Whether field is required
 * @var string $under_label Text under label
 * @var string $under_field Text under field
 * @var bool $shows_label_wrapper Whether to show label wrapper
 * @var bool $shows_under_field Whether to show under field text
 * @var string $field_type Field type
 * @var string $label_id HTML ID of the label
 * @var string $description_id HTML ID of the text under the label
 * @var string $help_id HTML ID of the text under the field
 * @var string $form_instance_suffix Deprecated: ID suffix of Elzo Forms 1.1 for repeated forms
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

// phpcs:disable WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound -- This template is loaded via Template_Loader::load_template() (function scope), so variables here are function-scoped, not globals.

?>
<div <?php echo $field->get_wrapper_attributes(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Attributes are escaped in Field::get_wrapper_attributes(). ?>>
    <?php if($shows_label_wrapper){ ?>
        <div class="elzo-forms-field-label-wrapper">
            <?php if($label){ ?>
                <?php if(in_array($field_type, ['checkbox', 'radio'], true)){ ?>
                    <div id="<?php echo esc_attr($label_id); ?>" class="elzo-forms-field-label">
                        <?php echo esc_html($label); ?>
                        <?php if($required){ ?><span class="elzo-forms-field-required-mark">*</span><?php } ?>
                    </div>
                <?php } else { ?>
                    <label for="<?php echo esc_attr($id); ?>" id="<?php echo esc_attr($label_id); ?>" class="elzo-forms-field-label">
                        <?php echo esc_html($label); ?>
                        <?php if($required){ ?><span class="elzo-forms-field-required-mark">*</span><?php } ?>
                    </label>
                <?php } ?>
            <?php } ?>
            <?php if($under_label){ ?>
                <div id="<?php echo esc_attr($description_id); ?>" class="elzo-forms-field-under-label"><?php echo wp_kses_post($under_label); ?></div>
            <?php } ?>
        </div>
    <?php } ?>
    <?php
        // Render field content - handles template loading and fallback to render_html()
        $field_html = $field->render([
            'form_settings' => $form_settings ?? [],
            'texts_settings' => $texts_settings ?? [],
            'form_id' => $form_id ?? null,
            'step_index' => $step_index ?? 0,
            'form_instance_suffix' => $form_instance_suffix ?? '',
        ]);

        // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Field markup is generated by trusted plugin templates where output escaping is handled per value.
        echo $field_html;
    ?>
    <?php if($shows_under_field){ ?>
        <div id="<?php echo esc_attr($help_id); ?>" class="elzo-forms-field-under-field"><?php echo wp_kses_post($under_field); ?></div>
    <?php } ?>
</div>
